<?php  

register_post_type('home_slide_1', array(
	'labels' => array(
		'name'	 => 'Home Slider 1',
		'singular_name' => 'Slide',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Slide' ),
		'view_item' => 'View Slide',
		'edit_item' => 'Edit Slide',
	    'new_item' => __('New Slide'),
	    'view_item' => __('View Slide'),
	    'search_items' => __('Search Slides'),
	    'not_found' =>  __('No slides found'),
	    'not_found_in_trash' => __('No slides found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'editor', 'page-attributes'),
	'menu_position' => 101,
));

register_post_type('home_slide_2', array(
	'labels' => array(
		'name'	 => 'Home Slider 2',
		'singular_name' => 'Slide',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Slide' ),
		'view_item' => 'View Slide',
		'edit_item' => 'Edit Slide',
	    'new_item' => __('New Slide'),
	    'view_item' => __('View Slide'),
	    'search_items' => __('Search Slides'),
	    'not_found' =>  __('No slides found'),
	    'not_found_in_trash' => __('No slides found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'page-attributes'),
	'menu_position' => 102,
));

register_post_type('home_slide_3', array(
	'labels' => array(
		'name'	 => 'Home Slider 3',
		'singular_name' => 'Slide',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Slide' ),
		'view_item' => 'View Slide',
		'edit_item' => 'Edit Slide',
	    'new_item' => __('New Slide'),
	    'view_item' => __('View Slide'),
	    'search_items' => __('Search Slides'),
	    'not_found' =>  __('No slides found'),
	    'not_found_in_trash' => __('No slides found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'editor', 'page-attributes'),
	'menu_position' => 103,
));

register_taxonomy(
    'program', 
    array('home_slide_3'), 
        array(
        'hierarchical' => true,
        'labels' => array(
        'name' => _x( 'Programs', 'taxonomy general name' ),
        'singular_name' => _x( 'Program', 'taxonomy singular name' ),
        'search_items' =>  __( 'Search Programs' ),
        'all_items' => __( 'All Programs' ),
        'parent_item' => __( 'Parent Program' ),
        'parent_item_colon' => __( 'Parent Program:' ),
        'edit_item' => __( 'Edit Program' ), 
        'update_item' => __( 'Update Program' ),
        'add_new_item' => __( 'Add New Program' ),
        'new_item_name' => __( 'New Program Name' ),
        'menu_name' => __( 'Programs' ),
    ),
    'show_ui' => true,
    'query_var' => true,
    'rewrite' => false,
));

register_post_type('gallery', array(
	'labels' => array(
		'name'	 => 'Student Gallery',
		'singular_name' => 'Gallery Entry',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Gallery Entry' ),
		'view_item' => 'View Gallery Entry',
		'edit_item' => 'Edit Gallery Entry',
	    'new_item' => __('New Gallery Entry'),
	    'view_item' => __('View Gallery Entry'),
	    'search_items' => __('Search Gallery'),
	    'not_found' =>  __('No entries found'),
	    'not_found_in_trash' => __('No entries found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'page-attributes', 'thumbnail', 'editor'),
	'menu_position' => 104,
));

register_taxonomy(
    'gallery_category', 
    array('gallery'), 
        array(
        'hierarchical' => true,
        'labels' => array(
        'name' => _x( 'Gallery Categories', 'taxonomy general name' ),
        'singular_name' => _x( 'Gallery Category', 'taxonomy singular name' ),
        'search_items' =>  __( 'Search Gallery Categories' ),
        'all_items' => __( 'All Gallery Categories' ),
        'parent_item' => __( 'Parent Gallery Category' ),
        'parent_item_colon' => __( 'Parent Gallery Category:' ),
        'edit_item' => __( 'Edit Gallery Category' ), 
        'update_item' => __( 'Update Gallery Category' ),
        'add_new_item' => __( 'Add New Gallery Category' ),
        'new_item_name' => __( 'New Gallery Category Name' ),
        'menu_name' => __( 'Gallery Categories' ),
    ),
    'show_ui' => true,
    'query_var' => true,
    'rewrite' => false,
));

register_post_type('custom-gallery', array(
	'labels' => array(
		'name'	 => 'Custom Gallery',
		'singular_name' => 'Gallery Entry',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Gallery Entry' ),
		'view_item' => 'View Gallery Entry',
		'edit_item' => 'Edit Gallery Entry',
	    'new_item' => __('New Gallery Entry'),
	    'view_item' => __('View Gallery Entry'),
	    'search_items' => __('Search Gallery'),
	    'not_found' =>  __('No entries found'),
	    'not_found_in_trash' => __('No entries found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'page-attributes', 'thumbnail', 'editor'),
	'menu_position' => 104,
));

register_taxonomy(
    'custom_gallery_category', 
    array('custom-gallery'), 
        array(
        'hierarchical' => true,
        'labels' => array(
        'name' => _x( 'Gallery Categories', 'taxonomy general name' ),
        'singular_name' => _x( 'Gallery Category', 'taxonomy singular name' ),
        'search_items' =>  __( 'Search Gallery Categories' ),
        'all_items' => __( 'All Gallery Categories' ),
        'parent_item' => __( 'Parent Gallery Category' ),
        'parent_item_colon' => __( 'Parent Gallery Category:' ),
        'edit_item' => __( 'Edit Gallery Category' ), 
        'update_item' => __( 'Update Gallery Category' ),
        'add_new_item' => __( 'Add New Gallery Category' ),
        'new_item_name' => __( 'New Gallery Category Name' ),
        'menu_name' => __( 'Gallery Categories' ),
    ),
    'show_ui' => true,
    'query_var' => true,
    'rewrite' => false,
));

register_post_type('student_life_slide', array(
	'labels' => array(
		'name'	 => 'Student Life Slider',
		'singular_name' => 'Slide',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Slide' ),
		'view_item' => 'View Slide',
		'edit_item' => 'Edit Slide',
	    'new_item' => __('New Slide'),
	    'view_item' => __('View Slide'),
	    'search_items' => __('Search Slides'),
	    'not_found' =>  __('No slides found'),
	    'not_found_in_trash' => __('No slides found in Trash'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => false,
	'query_var' => true,
	'supports' => array('title', 'editor', 'page-attributes'),
	'menu_position' => 105,
));

register_post_type('student', array(
	'labels' => array(
		'name'	 => 'Students',
		'singular_name' => 'Student',
		'add_new' => __( 'Add New' ),
		'add_new_item' => __( 'Add new Student' ),
		'view_item' => 'View Student',
		'edit_item' => 'Edit Student',
	    'new_item' => __('New Student'),
	    'view_item' => __('View Student'),
	    'search_items' => __('Search Students'),
	    'not_found' =>  __('No students found'),
	    'not_found_in_trash' => __('No students found in Trash'),
	),
	'public' => true,
	'exclude_from_search' => false,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'student',
		'with_front' => 'false'
	),
	'query_var' => true,
	'supports' => array('title', 'editor', 'page-attributes'),
	'menu_position' => 106,
));

?>